### Reminder ###

from the codebook 1.2 Code section:

While quantum circuits are represented as quantum functions, a quantum function alone isn't enough to run and execute a circuit. For this we need two extra parts:

- a device to run the circuit on
- a QNode, which binds the circuit to the device, and executes it

In [21]:
#I.3.1
import pennylane as qml
import numpy as np

dev = qml.device("default.qubit", wires=1) #1 Qubit
#dev = qml.device("default.qubit", wires="wire_a") ##wires -> list of names or a number (they represent qubits)

U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)

@qml.qnode(dev) ##  decorator function binds the circuit to the device and executes it
def apply_u():

    # USE QubitUnitary TO APPLY U TO THE QUBIT
    
    qml.QubitUnitary(U, wires=0) ### I believe 0 works because of indexing here, represents the first and only qubit
    #qml.QubitUnitary(U, wires="wire_a")
    # Return the state
    return qml.state()


###### if we dont use a decorator function, we have to do this:

# This creates a QNode, binding the function and device
my_qnode = qml.QNode(apply_u, dev)

# Now we can execute the QNode by calling it like we would a regular function
my_qnode(), apply_u() ## both print out the same result

(tensor([0.70710678+0.j, 0.70710678+0.j], requires_grad=True),
 tensor([0.70710678+0.j, 0.70710678+0.j], requires_grad=True))

https://docs.pennylane.ai/en/stable/code/api/pennylane.QubitUnitary.html

comparing to how I previously did it, I returned the matrix multiplication of u and the state (np.matmul), Xanadu used np.dot


- we also initialized a state ($|0\rangle$) beforehand
- apply_u, then measured state

In [3]:
print(dev)

Default qubit PennyLane plugin
Short name: default.qubit
Package: pennylane
Plugin version: 0.29.1
Author: Xanadu Inc.
Wires: 1
Shots: None


In [25]:
#1.3.2 #read the question carefully next time, accidentally typed out U rot matrix, Good way to check it
#gives the same output

dev = qml.device("default.qubit", wires=1)


@qml.qnode(dev)
def apply_u_as_rot(phi, theta, omega):

    ##################
    # YOUR CODE HERE #
    ##################
    
    #U = np.array([[np.exp(-1j*(phi+omega)/2)*np.cos(theta/2), -np.exp(1j*(phi-omega)/2)*np.sin(theta/2)], 
    #              [np.exp(-1j*(phi-omega)/2)*np.sin(theta/2),  np.exp(1j*(phi+omega)/2)*np.cos(theta/2)]])
                  
    
    # APPLY A ROT GATE USING THE PROVIDED INPUT PARAMETERS
    
    ##qml.QubitUnitary(U, wires=0)
    
    qml.Rot(phi, theta, omega, wires=0)
    
    # RETURN THE QUANTUM STATE VECTOR

    return qml.state()

apply_u_as_rot(np.pi, 0, 0)

tensor([6.123234e-17-1.j, 0.000000e+00+0.j], requires_grad=True)

In [26]:
dev = qml.device("default.qubit", wires=1)


@qml.qnode(dev)
def apply_u_as_rot(phi, theta, omega):

    ##################
    # YOUR CODE HERE #
    ##################
    
    U = np.array([[np.exp(-1j*(phi+omega)/2)*np.cos(theta/2), -np.exp(1j*(phi-omega)/2)*np.sin(theta/2)], 
                  [np.exp(-1j*(phi-omega)/2)*np.sin(theta/2),  np.exp(1j*(phi+omega)/2)*np.cos(theta/2)]])
                  
    
    # APPLY A ROT GATE USING THE PROVIDED INPUT PARAMETERS
    
    qml.QubitUnitary(U, wires=0)
    
    #qml.Rot(phi, theta, omega, wires=0)
    
    # RETURN THE QUANTUM STATE VECTOR

    return qml.state()

apply_u_as_rot(np.pi, 0, 0)

tensor([6.123234e-17-1.j, 0.000000e+00+0.j], requires_grad=True)